### ISSUE TITLE
Скетчи

### ISSUE THREAD

**Issue by chaos23d** [BMSTU2024/-#4]
Как примерно будет выглядеть

**Comment by chaos23d** [comment]
по поводу примерного интерфейса. При входе в игру есть возможность зарегистрироваться или войти уже с существующим аккаунтом. Далее есть возможность перейти к игре, перейти в чаты и перейти в настройки(пока не знаю что там будет). В чатах можно выбрать чат и там можно переписываться. При переходе к игре даётся выбор режима(много придётся отображать. Могу отдельно скинуть).
![Безымянный](https://github.com/user-attachments/assets/1ff74e6e-3e4b-4023-bd4e-c03fe92e4991)

**Comment by wldmr-key** [comment]
пока пойдет
